version: '3'
services:
  pyxtermjs:
    build: .
    image: crosslab/edrys_arduino_lab
    container_name: edrys_arduino_lab
    ports:
      - "5000:5000"
    environment:
      - PYXTERM_CMD=zsh
    devices:
      - /dev/ttyACM0
