---
id: RGcuinHsYMahUPiN-YxkK
createdBy: andre.dietrich@informatik.tu-freiberg.de
dateCreated: 1662980826456
name: Java Programming
members:
  teacher:
  - teacher@mail.de
  student: []
modules:
- url: https://cross-lab-project.github.io/edrys_module-editor/index.html
  config:
    file:
      HelloWorld.java: |
        public class HelloWorld {
            public static void main(String[] args) {
                System.out.println("Hello world!");
            }
        }
    runCommand: execute
    language: cpp
    theme: light
  studentConfig: ''
  teacherConfig: ''
  stationConfig: ''
  width: full
  height: tall
- url: https://cross-lab-project.github.io/edrys_module-pyxtermjs/index.html
  config: ''
  studentConfig: ''
  teacherConfig: ''
  stationConfig:
    server: http://localhost:5000/pty
    execute: execute
    script: javac HelloWorld.java && java HelloWorld
    enable:
      teacher: true
      student: true
  width: full
  height: tall
